### ISSUE TITLE
Propagation of all key events to JS

### ISSUE THREAD

**Issue by Urbiwanus** [petrsimon/cordova.externalkeyboard#2]
Hi, 

Dealing with external key events in IOS is a big problem. For instance you have a bluetooth keyboard / barcode scanner connected to your IOS mobile device. Its not possible to catch key events without having a focus on a certain input. ( On Android its easy to listen to external key events )

I would be great to get all external key events on JavaScript side to deal with them, Instead of defining some shortcuts. 

I m not sure if this is possible (No Xcode Dev ;-) )

Regards

**Comment by petrsimon** [comment]
I looked at this briefly, but it seems that there _was_ a way to use private APIs, but it seems unreliable for all keys. I guess it's security feature.
