### ISSUE TITLE
keyUp

### ISSUE THREAD

**Issue by redon** [petrsimon/cordova.externalkeyboard#4]
Hi Petr

single key shortcuts works very well! Thank you!
I even can stop the listener by setting the commands to

```
commands = "";
delimiter = "|";
cordova.plugins.ExternalKeyboard.setKeyCommands(commands, delimiter);
cordova.plugins.ExternalKeyboard.redraw();
```

So I can use the keybord with every key for a normal Input-Field.
Afterwards I restart the listener by setting the commands again.

Now I have a new idea ;-)

How about a onKeyUp event?
I have some objects on the screen, that you can move around by pressing one of the arrow keys.
as long as the key is pressed, the object moves, but it should stop when you release the key.

Cheers

**Comment by petrsimon** [comment]
Wonderful. Regarding the keyup event. It seems to be possible, but it's using something called private api, which might not get approved for App store. So if your application is supposed to be distributed via the App store, you should try to find another way to do it. Perhaps a second arrow press could cancel the action or press of the opposite arrow?

**Comment by redon** [comment]
Thank you for your response. It should be distributed in the App store, so I look for an other solution.
