### ISSUE TITLE
CordovaError: Failed to fetch plugin https://github.com/petrsimon/cordova.externalkeyboard.git

### ISSUE THREAD

**Issue by raghavdm** [petrsimon/cordova.externalkeyboard#6]
info using npm@5.6.0
info using node@v8.11.1

cordova version:- 8.0.0

giving error while installing:-
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: git+https://github.com/petrsimon/cordova.externalkeyboard.git.
npm ERR! package.json npm can't find a package.json file in your current directory.

**Comment by nive745** [comment]
I got same error. Please help me to overcome this problem. I am stuck with this problem.
npm@5.6.0
node@v8.11.3
cordova --version - 8.0.0

**Comment by petrsimon** [comment]
Sorry, I don't maintain the package anymore. Good luck finding the solution.
